name = "mabi-newcalculator"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MABI_CACHE"
id = "0643a6fce66341758a74388da03dfc8b"

[[d1_databases]]
binding = "MABI_DB"
database_name = "mabi-prices"
database_id = "2330f25e-8d63-4583-8771-bbd0e1f60edc"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
